In [18]:
import pandas as pd

In [19]:
data = pd.read_csv("Pokemon[1].csv")
data.head(n=10) #by default the head function shows only 5 rows

   #                       Name Type 1  ... Speed  Generation  Legendary
0  1                  Bulbasaur  Grass  ...    45           1      False
1  2                    Ivysaur  Grass  ...    60           1      False
2  3                   Venusaur  Grass  ...    80           1      False
3  3      VenusaurMega Venusaur  Grass  ...    80           1      False
4  4                 Charmander   Fire  ...    65           1      False
5  5                 Charmeleon   Fire  ...    80           1      False
6  6                  Charizard   Fire  ...   100           1      False
7  6  CharizardMega Charizard X   Fire  ...   100           1      False
8  6  CharizardMega Charizard Y   Fire  ...   100           1      False
9  7                   Squirtle  Water  ...    43           1      False

[10 rows x 13 columns]

In [20]:
speed_mean = data["Speed"].mean()

def set_speed(value):
    if value < speed_mean:
        return "Low Speed"
    elif value == speed_mean:
        return "Neutral Speed"
    else:
        return "High Speed"

In [21]:
hp_mean = data["HP"].mean()

def set_HP(hp):
  if hp < hp_mean:
    return "Low HP"
  elif hp==hp_mean:
    return "Neutral HP"
  else:
    return "High HP"

In [22]:
# "Speed_high_low"  -> "High Speed" , "Low Speed"
data["High_Low_Speed"] = data["Speed"].apply(set_speed)
data

       #                   Name   Type 1  ... Generation  Legendary  High_Low_Speed
0      1              Bulbasaur    Grass  ...          1      False       Low Speed
1      2                Ivysaur    Grass  ...          1      False       Low Speed
2      3               Venusaur    Grass  ...          1      False      High Speed
3      3  VenusaurMega Venusaur    Grass  ...          1      False      High Speed
4      4             Charmander     Fire  ...          1      False       Low Speed
..   ...                    ...      ...  ...        ...        ...             ...
795  719                Diancie     Rock  ...          6       True       Low Speed
796  719    DiancieMega Diancie     Rock  ...          6       True      High Speed
797  720    HoopaHoopa Confined  Psychic  ...          6       True      High Speed
798  720     HoopaHoopa Unbound  Psychic  ...          6       True      High Speed
799  721              Volcanion     Fire  ...          6       True      High Speed

[800 rows x 14 columns]

In [23]:
# "Speed_high_low"  -> "High Speed" , "Low Speed"
data["High_Low_HP"] = data["HP"].apply(set_HP)
data

       #                   Name   Type 1  ... Legendary  High_Low_Speed  High_Low_HP
0      1              Bulbasaur    Grass  ...     False       Low Speed       Low HP
1      2                Ivysaur    Grass  ...     False       Low Speed       Low HP
2      3               Venusaur    Grass  ...     False      High Speed      High HP
3      3  VenusaurMega Venusaur    Grass  ...     False      High Speed      High HP
4      4             Charmander     Fire  ...     False       Low Speed       Low HP
..   ...                    ...      ...  ...       ...             ...          ...
795  719                Diancie     Rock  ...      True       Low Speed       Low HP
796  719    DiancieMega Diancie     Rock  ...      True      High Speed       Low HP
797  720    HoopaHoopa Confined  Psychic  ...      True      High Speed      High HP
798  720     HoopaHoopa Unbound  Psychic  ...      True      High Speed      High HP
799  721              Volcanion     Fire  ...      True      High Speed      High HP

[800 rows x 15 columns]